### PR TITLE
Fix kernel 6.7 and 6.8 compat

### PR DESCRIPTION
**Pull request by svpcom**
- Fix kernel 6.7 and 6.8 compat
- Disable AP and P2P by default (it sometimes triggers DFS errors)
- Add card thermal reporting (but need to figure out how to convert to real temperature)

### CODE REVIEW

**Comment by libc0607** [comment]
> * Add card thermal reporting (but need to figure out how to convert to real temperature)


It seems that it's a typical CMOS temp sensor using Celsius (Kelvin) and needs single-point calibration 

Did a quick test of the thermal patch, 
 - My room (well-ventilated) temperature according to the weather forecast: 25 degrees Celsius
 - 8812EU module, with a small heat sink attached to the bottom 

And the (stabled) readout of thermal_value in procfs:
- After insmod, just idle: 20/20
- MCS15, filled the bandwidth with random data (via wfb-ng) going out: 41/39
- MCS15, filled the bandwidth with random data (via wfb-ng) going out, with a fan: 32/31 

It's weird that the offset read by phydm_get_multi_thermal_offset() keeps zero. 
Found EEPROM definition [here](https://github.com/libc0607/rtl88x2eu-20230815/blob/7e7a495c0dc9acc5659646344e27af9916f539c5/include/hal_pg.h#L813): 
```
#define	EEPROM_THERMAL_METER_A_8822E		0xD0
#define	EEPROM_THERMAL_METER_B_8822E		0xD1
```
and here's my BL-M8812EU2 EEPROM readout:  
```
/proc/net/rtl88x2eu/wlx9803cfcfa425$ cat efuse_map |grep 0xd0

0xd0	13 12 FF FF FF FF FF FF 	FF FF FF FF FF FF FF FF
``` 
hmmm... It somehow makes sense? If 39℃ is the 8812eu chip junction temperature when it's idle, and 60℃ when TX is full on.

**Comment by libc0607** [comment]
I've asked the LB-LINK PM about if they did the temperature calibration & if the scale is in Celsius/Kelvin. Expecting a reply on Monday.

**Comment by svpcom** [comment]
In my tests in idle (cold state) 19 - 20.  When tx at max power (txpower fixed 3000, heatsink + cooler) it is ~ 30 (but real temperature of heat sink measured by hand > 50C). So it seems gauge is not linear or we need to do some linear (kx + b) transformation

**Comment by svpcom** [comment]
Offset is also zero

**Comment by svpcom** [comment]
@libc0607 Also could you ask LB-LINK if this card has any protection against work without antenna or with unmatched antenna?  For example ac180 (high power card from Taobao on rtl8812au chipset) will burn in few seconds if run without antenna or if antenna has high SWR.

**Comment by libc0607** [comment]
> In my tests in idle (cold state) 19 - 20. When tx at max power (txpower fixed 3000, heatsink + cooler) it is ~ 30 (but real temperature of heat sink measured by hand > 50C). So it seems gauge is not linear or we need to do some linear (kx + b) transformation

Asking my friend doing analog CMOS design. He means If we assume Realtek is using the most common and robust temp sensor structure, then in theory it should be some (kx+b) transformation..

> @libc0607 Also could you ask LB-LINK if this card has any protection against work without antenna or with unmatched antenna? For example ac180 (high power card from Taobao on rtl8812au chipset) will burn in few seconds if run without antenna or if antenna has high SWR.

Asked. 

And I saved an image of someone in the Chinese QQ group accidentally burnt (other reason, not by losing the antenna) his 8812eu, and he teardown the chips. There seems no RF coupler or power detector here. Most likely no protection --but still waiting for his confirmation. 

QQ图片20240518233428

**Comment by libc0607** [comment]
Did some keyword searching, (assuming the temperature sensors are the same between those crab chips so not caring the ifdefs)

Code: when the temperature changes 20℃ (in the comment), do some calibrate:
[halphyrf_ap.c#L1501](https://github.com/libc0607/rtl88x2eu-20230815/blob/7e7a495c0dc9acc5659646344e27af9916f539c5/hal/phydm/halrf/halphyrf_ap.c#L1501): 
```
if ((delta_LCK >= c.threshold_iqk) && (!iqk_info->rfk_forbidden)) {
			/*Delta temperature is equal to or larger than 20 centigrade.*/
			dm->rf_calibrate_info.thermal_value_lck = thermal_value;
			(*c.phy_lc_calibrate)(dm);
		}
```
where the default value of ```threshold_iqk``` seems to be 8: 
[halrf_8822e.c#L1307](https://github.com/libc0607/rtl88x2eu-20230815/blob/7e7a495c0dc9acc5659646344e27af9916f539c5/hal/phydm/halrf/rtl8822e/halrf_8822e.c#L1307)
```
config->threshold_iqk = IQK_THRESHOLD;
```
[halrf.h#L468](https://github.com/libc0607/rtl88x2eu-20230815/blob/7e7a495c0dc9acc5659646344e27af9916f539c5/hal/phydm/halrf/halrf.h#L468): 
```
#define IQK_THRESHOLD 8
```
That may indicate the slope is 2.5. Seems closer to the heat sink's feeling😂

I guess the efuse thermal value may equal the readout measured in some certain temperature. And I find it has some default values [here](https://github.com/libc0607/rtl88x2eu-20230815/blob/7e7a495c0dc9acc5659646344e27af9916f539c5/include/hal_pg.h#L876), most likely the value near 25℃ (analog CMOS design always start from here).

**Comment by svpcom** [comment]
@libc0607 KCT8528HE it seems have power detector accoring to datasheet, but I'm not sure that wifi module designer use it.

```
KCT8528HE is a 5GHz RF Front-End Integrated Circuit which incorporates key
RF functionality needed for IEEE 802.11a/n/ac/ax WLAN systems operating in
the 5.15-5.85GHz range. KCT8528HE integrates a high-efficiency, high-linearity
power amplifier (PA), a low noise amplifier (LNA) with bypass, a SPDT
transmit/receive (T/R) switch and harmonic filters all in one device.

The LNA and PA disable functions ensure low leakage current while switched
off. A power detector is also integrated to provide close-loop power control within
the system.
```

изображение

**Comment by libc0607** [comment]
Since almost all Chinese chips are aiming at being "a domestic replacement", the pin definition always keeps the same with Western products. In this case, I guess it's [SKY85743](https://edit.wpgdadawant.com/uploads/news_file/program/2020/35558/tech_files/program_35558_suggest_other_file.PDF). So the VDET pin is here. Unfortunately, it seems not been used. 

image


And I don't know if the integrated detector can distinguish the transmitted power and the reflected power (maybe an integrated directional coupler is needed), the datasheet has very limited details.

**Comment by svpcom** [comment]
@libc0607 But how cards like Alfa awus036ach doesn't burn without antennas?

изображение

**Comment by libc0607** [comment]
Some FEM has an integrated coupler so that it can detect reflected power. If the coupler exists, it will always be illustrated in the block diagram (for marketing). For example, [SKY85747](https://www.skyworksinc.com/-/media/SkyWorks/Documents/Products/2701-2800/SKY85747-11_203929N.pdf):  
image

[QPF4588](https://www.mouser.com/pdfdocs/QPF4588ProductDataSheet.pdf):
image

I don't know the Alfa's FEM detail but I think it should be something like them. And the KCT8528HE datasheet never mentioned that. :(

**Comment by svpcom** [comment]
@libc0607 Anyway in picture above coupler has wrong direction - it measure only direct power, not reflected from antenna. It seems that for high-power cards it is necessary to add coupler (and some logic that will cut amplifier power in case of high reflected signal and/or temperature) manually

**Comment by libc0607** [comment]
>  It seems that for high-power cards it is necessary to add coupler (and some logic that will cut amplifier power in case of high reflected signal and/or temperature) manually

Agree. 

But there seem no things like a cheap "VSWR protection module" on sale. I think I can start making something from a microstrip coupler on a 2-layer FR-4 PCB ... as it's only a protector and needs less accuracy. 

And where should "the logic" happen?  Works like a pure hardware fuse to cut power, or send feedback to wfb-ng (via UART/I2C/GPIO/etc.)?

**Comment by libc0607** [comment]
btw, I've asked the LB-LINK PM 2 times about what the thermal sensor doing, and he didn't reply to me. (

Decide to merge it first because it contains useful thermal information anyway.

**Comment by svpcom** [comment]
> And where should "the logic" happen? Works like a pure hardware fuse to cut power, or send feedback to wfb-ng (via UART/I2C/GPIO/etc.)?

I'll prefer to cut amplifier's power fast in such case. But need to add some feedback to wfb-ng to show warning to user. Does 8812eu have any spare GPIO pins to use them for this case?

**Comment by libc0607** [comment]
There are three testpoints, GPIO 5/6/7, but inside the shield. No GPIOs on the breakout or FPC connector.

image

**Comment by libc0607** [comment]
The LB-LINK PM finally replied. He said:
 - bl-m8812eu2 has no unmatch protection
 - Their process “does not involve thermal sensor calibration”
 - The temperature compensation of the RF part is done in 60°C ~ 70°C
 
Seems they really don't know there's a temperature sensor inside the chip. 😂

**Comment by libc0607** [comment]
> That may indicate the slope is 2.5. Seems closer to the heat sink's feeling😂
> 
> I guess the efuse thermal value may equal the readout measured in some certain temperature. And I find it has some default values [here](https://github.com/libc0607/rtl88x2eu-20230815/blob/7e7a495c0dc9acc5659646344e27af9916f539c5/include/hal_pg.h#L876), most likely the value near 25℃ (analog CMOS design always start from here).

Gonna find a sensor to validate this, as it really close to my feeling

**Pull request merged**
